.data
.pushsection .hyp.reloc, "a"
.global __hyp_section_.hyp.idmap.text
.word 0
.reloc 0, R_AARCH64_PREL32, __hyp_section_.hyp.idmap.text + 0xb70
.word 0
.reloc 4, R_AARCH64_PREL32, __hyp_section_.hyp.idmap.text + 0xb78
.global __hyp_section_.hyp.text
.global __hyp_section_.hyp.rodata
.word 0
.reloc 8, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x238
.word 0
.reloc 12, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x258
.word 0
.reloc 16, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x268
.word 0
.reloc 20, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e0
.word 0
.reloc 24, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e8
.word 0
.reloc 28, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x320
.word 0
.reloc 32, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x340
.word 0
.reloc 36, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3c0
.word 0
.reloc 40, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5d8
.word 0
.reloc 44, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5e0
.word 0
.reloc 48, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5e8
.word 0
.reloc 52, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5f0
.word 0
.reloc 56, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5f8
.word 0
.reloc 60, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x600
.word 0
.reloc 64, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x608
.word 0
.reloc 68, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x610
.word 0
.reloc 72, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x618
.word 0
.reloc 76, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x620
.word 0
.reloc 80, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x628
.word 0
.reloc 84, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x630
.word 0
.reloc 88, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x638
.word 0
.reloc 92, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x640
.word 0
.reloc 96, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x648
.word 0
.reloc 100, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x650
.word 0
.reloc 104, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x658
.word 0
.reloc 108, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x660
.word 0
.reloc 112, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x668
.word 0
.reloc 116, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x670
.word 0
.reloc 120, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x678
.word 0
.reloc 124, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x680
.word 0
.reloc 128, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x688
.word 0
.reloc 132, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x690
.word 0
.reloc 136, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x698
.word 0
.reloc 140, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x19f8
.word 0
.reloc 144, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1a10
.word 0
.reloc 148, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1a48
.word 0
.reloc 152, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1a60
.word 0
.reloc 156, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1a98
.word 0
.reloc 160, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ab0
.word 0
.reloc 164, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ae8
.word 0
.reloc 168, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1b00
.word 0
.reloc 172, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1b38
.word 0
.reloc 176, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1b50
.word 0
.reloc 180, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1b88
.word 0
.reloc 184, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ba0
.word 0
.reloc 188, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1bd8
.word 0
.reloc 192, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1bf0
.word 0
.reloc 196, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c28
.word 0
.reloc 200, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c40
.word 0
.reloc 204, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c78
.word 0
.reloc 208, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1c90
.word 0
.reloc 212, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1cc8
.word 0
.reloc 216, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ce0
.word 0
.reloc 220, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1d18
.word 0
.reloc 224, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1d30
.word 0
.reloc 228, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1d68
.word 0
.reloc 232, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1d80
.word 0
.reloc 236, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1db8
.word 0
.reloc 240, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1dd0
.word 0
.reloc 244, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e08
.word 0
.reloc 248, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e20
.word 0
.reloc 252, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e58
.word 0
.reloc 256, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e70
.word 0
.reloc 260, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ea8
.word 0
.reloc 264, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ec0
.word 0
.reloc 268, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ef8
.word 0
.reloc 272, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f10
.word 0
.reloc 276, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f48
.word 0
.reloc 280, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f60
.word 0
.reloc 284, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f98
.word 0
.reloc 288, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1fb0
.word 0
.reloc 292, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2000
.word 0
.reloc 296, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2038
.word 0
.reloc 300, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2050
.word 0
.reloc 304, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2088
.word 0
.reloc 308, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x20a0
.word 0
.reloc 312, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x20d8
.word 0
.reloc 316, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x20f0
.word 0
.reloc 320, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2140
.word 0
.reloc 324, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2178
.word 0
.reloc 328, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2190
.word 0
.reloc 332, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x21c8
.word 0
.reloc 336, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x21e0
.word 0
.reloc 340, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2230
.word 0
.reloc 344, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2280
.word 0
.reloc 348, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x22b8
.word 0
.reloc 352, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x22d0
.word 0
.reloc 356, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2320
.word 0
.reloc 360, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2370
.word 0
.reloc 364, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x23c0
.word 0
.reloc 368, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x23f8
.word 0
.reloc 372, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2410
.word 0
.reloc 376, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2448
.word 0
.reloc 380, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2460
.word 0
.reloc 384, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x24b0
.word 0
.reloc 388, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2500
.word 0
.reloc 392, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2538
.word 0
.reloc 396, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2550
.word 0
.reloc 400, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2588
.word 0
.reloc 404, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x25a0
.word 0
.reloc 408, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x25f0
.word 0
.reloc 412, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2640
.word 0
.reloc 416, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2678
.word 0
.reloc 420, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2690
.word 0
.reloc 424, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x26c8
.word 0
.reloc 428, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x26e0
.word 0
.reloc 432, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2718
.word 0
.reloc 436, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2730
.word 0
.reloc 440, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2780
.word 0
.reloc 444, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x27d0
.word 0
.reloc 448, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2820
.word 0
.reloc 452, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2870
.word 0
.reloc 456, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x28c0
.word 0
.reloc 460, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x28f8
.word 0
.reloc 464, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2910
.word 0
.reloc 468, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2948
.word 0
.reloc 472, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2960
.word 0
.reloc 476, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2998
.word 0
.reloc 480, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x29b0
.word 0
.reloc 484, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a00
.word 0
.reloc 488, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a50
.word 0
.reloc 492, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2aa0
.word 0
.reloc 496, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2af0
.word 0
.reloc 500, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b40
.word 0
.reloc 504, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b78
.word 0
.reloc 508, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b90
.word 0
.reloc 512, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2bc8
.word 0
.reloc 516, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2be0
.word 0
.reloc 520, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c18
.word 0
.reloc 524, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c30
.word 0
.reloc 528, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c68
.word 0
.reloc 532, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c80
.word 0
.reloc 536, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2cb8
.word 0
.reloc 540, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2cd0
.word 0
.reloc 544, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d08
.word 0
.reloc 548, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d20
.word 0
.reloc 552, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d58
.word 0
.reloc 556, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d70
.word 0
.reloc 560, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2da8
.word 0
.reloc 564, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2dc0
.word 0
.reloc 568, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2df8
.word 0
.reloc 572, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e48
.word 0
.reloc 576, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e98
.word 0
.reloc 580, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ee8
.word 0
.reloc 584, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f00
.word 0
.reloc 588, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f38
.word 0
.reloc 592, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f88
.word 0
.reloc 596, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2fd8
.word 0
.reloc 600, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3028
.word 0
.reloc 604, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3078
.word 0
.reloc 608, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x30c8
.word 0
.reloc 612, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3118
.popsection
