/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for ksmbd_spnego_negtokeninit
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder ksmbd_spnego_negtokeninit_decoder;

extern int ksmbd_gssapi_this_mech(void *, size_t, unsigned char, const void *, size_t);
extern int ksmbd_neg_token_init_mech_token(void *, size_t, unsigned char, const void *, size_t);
extern int ksmbd_neg_token_init_mech_type(void *, size_t, unsigned char, const void *, size_t);

