/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for ksmbd_spnego_negtokentarg
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder ksmbd_spnego_negtokentarg_decoder;

extern int ksmbd_neg_token_targ_resp_token(void *, size_t, unsigned char, const void *, size_t);

