/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for ecdsasignature
 */
#include <linux/asn1_ber_bytecode.h>
#include "ecdsasignature.asn1.h"

enum ecdsasignature_actions {
	ACT_ecdsa_get_signature_r = 0,
	ACT_ecdsa_get_signature_s = 1,
	NR__ecdsasignature_actions = 2
};

static const asn1_action_t ecdsasignature_action_table[NR__ecdsasignature_actions] = {
	[   0] = ecdsa_get_signature_r,
	[   1] = ecdsa_get_signature_s,
};

static const unsigned char ecdsasignature_machine[] = {
	// ECDSASignature
	[   0] = ASN1_OP_MATCH,
	[   1] = _tag(UNIV, CONS, SEQ),
	[   2] =  ASN1_OP_MATCH_ACT,		// r
	[   3] =  _tag(UNIV, PRIM, INT),
	[   4] =  _action(ACT_ecdsa_get_signature_r),
	[   5] =  ASN1_OP_MATCH_ACT,		// s
	[   6] =  _tag(UNIV, PRIM, INT),
	[   7] =  _action(ACT_ecdsa_get_signature_s),
	[   8] = ASN1_OP_END_SEQ,
	[   9] = ASN1_OP_COMPLETE,
};

const struct asn1_decoder ecdsasignature_decoder = {
	.machine = ecdsasignature_machine,
	.machlen = sizeof(ecdsasignature_machine),
	.actions = ecdsasignature_action_table,
};
