/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for ecdsasignature
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder ecdsasignature_decoder;

extern int ecdsa_get_signature_r(void *, size_t, unsigned char, const void *, size_t);
extern int ecdsa_get_signature_s(void *, size_t, unsigned char, const void *, size_t);

